language: node_js

# Version of node to use
node_js:
  - "5"

env:
  global:
    - TRAVIS_BUILD_DIR=`pwd`/public/

before_script:

  - cd public/
  - npm install -g bower
  - npm install
  - bower install
  
script: 
  - gulp make
  - gulp build
