language: node_js

services:
  - mysql

# Version of node to use
node_js:
  - "5"

env:
  global:
    - TRAVIS_BUILD_DIR=`pwd`/public/

before_script:

  - mysql -e 'create database projet;'
  - mysql projet < DumpTheBase.sql

  - cd public/
  - npm install -g bower
  - npm install
  - bower install
  
script: 
  - gulp make
  - gulp build
