angular.module("app").controller 'sidenavCtrl', [
  '$scope'
  '$mdSidenav'
  ($scope, $mdSidenav) ->

    $scope.toggleSidenav = (menuId) ->
      $mdSidenav(menuId).toggle()

    $scope.menu = [
      {
        link: ''
        title: 'Dashboard'
        icon: 'dashboard'
      }
      {
        link: ''
        title: 'Friends'
        icon: 'group'
      }
      {
        link: ''
        title: 'Messages'
        icon: 'message'
      }
    ]
    $scope.admin = [
      {
        link: ''
        title: 'Trash'
        icon: 'delete'
      }
      {
        link: 'showListBottomSheet($event)'
        title: 'Settings'
        icon: 'settings'
      }
    ]
]

# ---
# generated by js2coffee 2.2.0